<dict>
	<string name="prefab">prefabs/moon_temple_common/256x512/256x512_cap_n_chest_selector.pfb</string>
	<array name="layout">
		<a><s>x</s></a>
		<a><s>s</s></a>
	</array>
	
	<int name="chance">1</int>
	<!-- <string name="placement">spread</string> -->
	<string name="reqs">chest</string>
</dict>
<dict>
	<string name="prefab">prefabs/moon_temple_common/256x512/256x512_cap_s_chest_selector.pfb</string>
	<array name="layout">
		<a><s>n</s></a>
		<a><s>x</s></a>
	</array>
	
	<int name="chance">1</int>
	<!-- <string name="placement">spread</string> -->
	<string name="reqs">chest</string>
</dict>

<dict>
	<string name="prefab">prefabs/moon_temple_common/512x256/512x256_cap_e_chest_selector.pfb</string>
	<array name="layout">
		<a><s>w</s><s>x</s></a>
	</array>
	
	<int name="chance">1</int>
	<!-- <string name="placement">spread</string> -->
	<string name="reqs">chest</string>
</dict>
<dict>
	<string name="prefab">prefabs/moon_temple_common/512x256/512x256_cap_w_chest_selector.pfb</string>
	<array name="layout">
		<a><s>x</s><s>e</s></a>
	</array>
	
	<int name="chance">1</int>
	<!-- <string name="placement">spread</string> -->
	<string name="reqs">chest</string>
</dict>

<dict>
	<string name="prefab">prefabs/moon_temple_common/512x512/512x512_room_chest_selector.pfb</string>
	<array name="layout">
		<a><s>nw</s><s>ne</s></a>
		<a><s>sw</s><s>se</s></a>
	</array>
	
	<int name="chance">1</int>
	<!-- <string name="placement">spread</string> -->
	<string name="reqs">chest</string>
</dict>

<dict>
	<string name="prefab">prefabs/moon_temple_common/512x512/512x512_cap_n_chest_selector.pfb</string>
	<array name="layout">
		<a><s>x</s><s>x</s></a>
		<a><s>s</s><s>s</s></a>
	</array>
	
	<int name="chance">1</int>
	<!-- <string name="placement">spread</string> -->
	<string name="reqs">chest</string>
</dict>