<dict>
	<string name="prefab">prefabs/moon_temple_common/256x256/256x256_cap_w_selector.pfb</string>
	<array name="layout">
		<a><s>e</s></a>
	</array>
	
	<int name="chance">1</int>
	<string name="reqs">small_cap</string>
</dict>
<dict>
	<string name="prefab">prefabs/moon_temple_common/256x256/256x256_cap_e_selector.pfb</string>
	<array name="layout">
		<a><s>w</s></a>
	</array>
	
	<int name="chance">1</int>
	<string name="reqs">small_cap</string>
</dict>