<dict>
	<string name="prefab">prefabs/moon_temple_common/256x512/256x512_cap_e_selector.pfb</string>
	<array name="layout">
		<a><s>w</s></a>
		<a><s>w</s></a>
	</array>
	
	<int name="chance">2</int>
	<string name="reqs">medium_cap</string>
</dict>
<dict>
	<string name="prefab">prefabs/moon_temple_common/256x512/256x512_cap_w_selector.pfb</string>
	<array name="layout">
		<a><s>e</s></a>
		<a><s>e</s></a>
	</array>
	
	<int name="chance">2</int>
	<string name="reqs">medium_cap</string>
</dict>

<dict>
	<string name="prefab">prefabs/moon_temple_common/256x512/256x512_sides_h_selector.pfb</string>
	<array name="layout">
		<a><s>we</s></a>
		<a><s>we</s></a>
	</array>
	
	<int name="chance">2</int>
	<string name="reqs">medium_cap</string>
</dict>