<dict>
	<string name="prefab">prefabs/moon_temple_common/512x512/512x512_cap_e_selector.pfb</string>
	<array name="layout">
		<a><s>w</s><s>x</s></a>
		<a><s>w</s><s>x</s></a>
	</array>
	
	<int name="chance">1</int>
	<string name="reqs">large_cap</string>
</dict>

<dict>
	<string name="prefab">prefabs/moon_temple_common/512x512/512x512_cap_w_selector.pfb</string>
	<array name="layout">
		<a><s>x</s><s>e</s></a>
		<a><s>x</s><s>e</s></a>
	</array>
	
	<int name="chance">1</int>
	<string name="reqs">large_cap</string>
</dict>

<dict>
	<string name="prefab">prefabs/moon_temple_common/512x512/512x512_sides_h_selector.pfb</string>
	<array name="layout">
		<a><s>w</s><s>e</s></a>
		<a><s>w</s><s>e</s></a>
	</array>
	
	<int name="chance">1</int>
	<string name="reqs">large_cap</string>
</dict>