<dict>
	<string name="prefab">prefabs/moon_temple_common/256x256/256x256_crn_nw_selector.pfb</string>
	<array name="layout">
		<a><s>se</s></a>
	</array>
	
	<int name="chance">2</int>
</dict>
<dict>
	<string name="prefab">prefabs/moon_temple_common/256x256/256x256_crn_ne_selector.pfb</string>
	<array name="layout">
		<a><s>sw</s></a>
	</array>
	
	<int name="chance">2</int>
</dict>		
<dict>
	<string name="prefab">prefabs/moon_temple_common/256x256/256x256_crn_sw_selector.pfb</string>
	<array name="layout">
		<a><s>ne</s></a>
	</array>
	
	<int name="chance">2</int>
</dict>
<dict>
	<string name="prefab">prefabs/moon_temple_common/256x256/256x256_crn_se_selector.pfb</string>
	<array name="layout">
		<a><s>nw</s></a>
	</array>
	
	<int name="chance">2</int>
</dict>