<dict>
	<string name="prefab">prefabs/moon_temple_common/512x512/512x512_crn_ne_selector.pfb</string>
	<array name="layout">
		<a><s>w</s><s>x</s></a>
		<a><s>sw</s><s>s</s></a>
	</array>
	
	<int name="chance">2</int>
</dict>
<dict>
	<string name="prefab">prefabs/moon_temple_common/512x512/512x512_crn_nw_selector.pfb</string>
	<array name="layout">
		<a><s>x</s><s>e</s></a>
		<a><s>s</s><s>se</s></a>
	</array>
	
	<int name="chance">2</int>
</dict>
<dict>
	<string name="prefab">prefabs/moon_temple_common/512x512/512x512_crn_se_selector.pfb</string>
	<array name="layout">
		<a><s>nw</s><s>n</s></a>
		<a><s>w</s><s>x</s></a>
	</array>
	
	<int name="chance">2</int>
</dict>
<dict>
	<string name="prefab">prefabs/moon_temple_common/512x512/512x512_crn_sw_selector.pfb</string>
	<array name="layout">
		<a><s>n</s><s>ne</s></a>
		<a><s>x</s><s>e</s></a>
	</array>
	
	<int name="chance">2</int>
</dict>