<dict>
	<string name="prefab">prefabs/moon_temple_common/512x512/512x512_room_selector.pfb</string>
	<array name="layout">
		<a><s>nw</s><s>ne</s></a>
		<a><s>sw</s><s>se</s></a>
	</array>
	
	<int name="chance">3</int>
</dict>

<dict>
	<string name="prefab">prefabs/moon_temple_common/512x512/512x512_diag_ne_sw_selector.pfb</string>
	<array name="layout">
		<a><s>x</s><s>ne</s></a>
		<a><s>sw</s><s>x</s></a>
	</array>
	
	<int name="chance">3</int>
</dict>
<dict>
	<string name="prefab">prefabs/moon_temple_common/512x512/512x512_diag_nw_se_selector.pfb</string>
	<array name="layout">
		<a><s>nw</s><s>x</s></a>
		<a><s>x</s><s>se</s></a>
	</array>
	
	<int name="chance">3</int>
</dict>

<dict>
	<string name="prefab">prefabs/moon_temple_common/512x512/512x512_x_e_selector.pfb</string>
	<array name="layout">
		<a><s>nw</s><s>x</s></a>
		<a><s>sw</s><s>x</s></a>
	</array>
	
	<int name="chance">3</int>
</dict>
<dict>
	<string name="prefab">prefabs/moon_temple_common/512x512/512x512_x_n_selector.pfb</string>
	<array name="layout">
		<a><s>x</s><s>x</s></a>
		<a><s>sw</s><s>se</s></a>
	</array>
	
	<int name="chance">3</int>
</dict>
<dict>
	<string name="prefab">prefabs/moon_temple_common/512x512/512x512_x_s_selector.pfb</string>
	<array name="layout">
		<a><s>nw</s><s>ne</s></a>
		<a><s>x</s><s>x</s></a>
	</array>
	
	<int name="chance">3</int>
</dict>
<dict>
	<string name="prefab">prefabs/moon_temple_common/512x512/512x512_x_w_selector.pfb</string>
	<array name="layout">
		<a><s>x</s><s>ne</s></a>
		<a><s>x</s><s>se</s></a>
	</array>
	
	<int name="chance">3</int>
</dict>