<dict>
	<string name="prefab">prefabs/moon_temple_common/256x512/256x512_crn_ne_selector.pfb</string>
	<array name="layout">
		<a><s>w</s></a>
		<a><s>sw</s></a>
	</array>
	
	<int name="chance">4</int>
</dict>
<dict>
	<string name="prefab">prefabs/moon_temple_common/256x512/256x512_crn_nw_selector.pfb</string>
	<array name="layout">
		<a><s>e</s></a>
		<a><s>se</s></a>
	</array>
	
	<int name="chance">4</int>
</dict>
<dict>
	<string name="prefab">prefabs/moon_temple_common/256x512/256x512_crn_se_selector.pfb</string>
	<array name="layout">
		<a><s>nw</s></a>
		<a><s>w</s></a>
	</array>
	
	<int name="chance">4</int>
</dict>
<dict>
	<string name="prefab">prefabs/moon_temple_common/256x512/256x512_crn_sw_selector.pfb</string>
	<array name="layout">
		<a><s>ne</s></a>
		<a><s>e</s></a>
	</array>
	
	<int name="chance">4</int>
</dict>