<dict>
	<string name="prefab">prefabs/moon_temple_common/512x256/512x256_gt_cap_e.pfb</string>
	<array name="layout">
		<a><s>W</s><s>x</s></a>
	</array>
	
	<bool name="hidden">true</bool>
	<int name="chance">1</int>
	<string name="reqs">gt</string>
	<!-- <string name="placement">right</string> -->
</dict>

<dict>
	<string name="prefab">prefabs/moon_temple_common/512x256/512x256_gt_cap_w.pfb</string>
	<array name="layout">
		<a><s>x</s><s>E</s></a>
	</array>
	
	<bool name="hidden">true</bool>
	<int name="chance">1</int>
	<string name="reqs">gt</string>
	<!-- <string name="placement">left</string> -->
</dict>

<dict>
	<string name="prefab">prefabs/moon_temple_common/256x512/256x512_gt_cap_n.pfb</string>
	<array name="layout">
		<a><s>x</s></a>
		<a><s>S</s></a>
	</array>
	
	<bool name="hidden">true</bool>
	<int name="chance">0</int>
	<string name="reqs">gt</string>
	<!-- <string name="placement">top</string> -->
</dict>

<dict>
	<string name="prefab">prefabs/moon_temple_common/256x512/256x512_gt_cap_s.pfb</string>
	<array name="layout">
		<a><s>N</s></a>
		<a><s>x</s></a>
	</array>
	
	<bool name="hidden">true</bool>
	<int name="chance">0</int>
	<string name="reqs">gt</string>
	<!-- <string name="placement">bottom</string> -->
</dict>