<sprite name="arrow-left" texture="gui/widget.png"><frame>33 42 12 28</frame></sprite>
<sprite name="arrow-left-hover" texture="gui/widget.png"><frame>45 42 12 28</frame></sprite>
<sprite name="arrow-left-down" texture="gui/widget.png"><frame>57 42 12 28</frame></sprite>
<sprite name="arrow-left-disabled" texture="gui/widget.png"><frame>69 42 12 28</frame></sprite>

<sprite name="arrow-right" texture="gui/widget.png"><frame>33 70 12 28</frame></sprite>
<sprite name="arrow-right-hover" texture="gui/widget.png"><frame>45 70 12 28</frame></sprite>
<sprite name="arrow-right-down" texture="gui/widget.png"><frame>57 70 12 28</frame></sprite>
<sprite name="arrow-right-disabled" texture="gui/widget.png"><frame>69 70 12 28</frame></sprite>

<sprite name="big-frame" texture="gui/playermenu.png"><frame>337 2 28 28</frame></sprite>
<sprite name="character-info-frame" texture="gui/playermenu.png"><frame>7 41 3 28</frame></sprite>

<sprite name="frame-line-horizontal" texture="gui/playermenu.png"><frame>2 20 328 3</frame></sprite>

%include "gui/dlc_sprites.inc"
