<sprite name="slider-button-left" texture="gui/widget.png"><frame>33 42 12 28</frame></sprite>
<sprite name="slider-button-left-hover" texture="gui/widget.png"><frame>45 42 12 28</frame></sprite>
<sprite name="slider-button-left-down" texture="gui/widget.png"><frame>57 42 12 28</frame></sprite>
<sprite name="slider-button-left-disabled" texture="gui/widget.png"><frame>69 42 12 28</frame></sprite>

<sprite name="slider-button-right" texture="gui/widget.png"><frame>33 70 12 28</frame></sprite>
<sprite name="slider-button-right-hover" texture="gui/widget.png"><frame>45 70 12 28</frame></sprite>
<sprite name="slider-button-right-down" texture="gui/widget.png"><frame>57 70 12 28</frame></sprite>
<sprite name="slider-button-right-disabled" texture="gui/widget.png"><frame>69 70 12 28</frame></sprite>
