<sprite name="slider-value" texture="gui/widget.png"><frame>132 78 26 18</frame></sprite>

<sprite name="slider-button-left" texture="gui/widget.png"><frame>125 0 12 18</frame></sprite>
<sprite name="slider-button-left-hover" texture="gui/widget.png"><frame>137 0 12 18</frame></sprite>
<sprite name="slider-button-left-down" texture="gui/widget.png"><frame>149 0 12 18</frame></sprite>

<sprite name="slider-button-right" texture="gui/widget.png"><frame>125 18 12 18</frame></sprite>
<sprite name="slider-button-right-hover" texture="gui/widget.png"><frame>137 18 12 18</frame></sprite>
<sprite name="slider-button-right-down" texture="gui/widget.png"><frame>149 18 12 18</frame></sprite>
