<unit slot="doodad" layer="-50">
	<scenes>
		<scene>
			<minimap_sprite origin="0 0" texture="gui/minimap.png" frame="32 0 2 4"/>
			<collision static="true">
				<rect shoot-through="true" aim-through="true">-8 0 8 16</rect>
			</collision>
			<sprite origin="0 0" texture="./_ledge.png" material="system/default.mats:floor">
				<frame>8 48 8 16</frame>
			</sprite>
		</scene>
	</scenes>
</unit>