<unit slot="doodad" layer="-50">
	<scenes>
		<scene>
			<minimap_sprite origin="0 0" texture="gui/minimap.png" frame="24 0 2 2"/>
			<collision static="true">
				<rect shoot-through="true" aim-through="true">0 -8 8 8</rect>
			</collision>				
			<sprite origin="0 0" texture="./_ledge.png" material="system/default.mats:floor">
				<frame>48 40 8 8</frame>
			</sprite>
		</scene>
	</scenes>
</unit>