<unit slot="doodad">
	<scenes default="1 2 3" empty="4" mushroom="5 6">
		<scene name="1">
			<sprite origin="-8 9" texture="./base.png" material="system/default.mats:proj-wall">
				<frame>96 32 19 9</frame>
			</sprite>	
			<sprite origin="-8 15" ulayer="1" texture="./base.png" material="system/default.mats:proj-wall">
				<frame>96 41 16 13</frame>
			</sprite>				
			
		</scene>	
		<scene name="2">
			<sprite origin="-8 9" texture="./base.png" material="system/default.mats:proj-wall">
				<frame>96 32 19 9</frame>
			</sprite>	
			<sprite origin="-8 15" ulayer="1" texture="./base.png" material="system/default.mats:proj-wall">
				<frame>96 54 16 12</frame>
			</sprite>				
			
		</scene>	
		<scene name="3">
			<sprite origin="-8 9" texture="./base.png" material="system/default.mats:proj-wall">
				<frame>96 32 19 9</frame>
			</sprite>	
			<sprite origin="-8 15" ulayer="1" texture="./base.png" material="system/default.mats:proj-wall">
				<frame>96 67 16 12</frame>
			</sprite>				
			
		</scene>		
		<scene name="4">
			<sprite origin="-8 9" texture="./base.png" material="system/default.mats:proj-wall">
				<frame>96 32 19 9</frame>
			</sprite>				
			
		</scene>		
		<scene name="5">
			<sprite origin="-8 9" texture="./base.png" material="system/default.mats:proj-wall">
				<frame>96 32 19 9</frame>
			</sprite>	
			<sprite origin="-8 15" ulayer="1" texture="./base.png" material="system/default.mats:proj-wall">
				<frame>96 79 16 12</frame>
			</sprite>						
			
		</scene>	
		<scene name="6">
			<sprite origin="-8 9" texture="./base.png" material="system/default.mats:proj-wall">
				<frame>96 32 19 9</frame>
			</sprite>	
			<sprite origin="-8 15" ulayer="1" texture="./base.png" material="system/default.mats:proj-wall">
				<frame>96 91 16 12</frame>
			</sprite>						
			
		</scene>					
	</scenes>
</unit>