<unit slot="doodad">
	<scenes>
		<scene>
			<minimap_sprite origin="0 -4" texture="gui/minimap.png" frame="0 0 4 8" />
			<collision static="true">
				<rect>0 14 16 36</rect>
			</collision>
			<sprite origin="0 16" texture="./base.png" material="system/default.mats:wall">
				<frame>32 48 16 32</frame>
			</sprite>
			<shadow darkness="1">
				<rect>0 16 16 32</rect>
			</shadow>
		</scene>
	</scenes>
</unit>
