<sprite name="arrow-down" texture="gui/widget.png"><frame>132 53 5 4</frame></sprite>
<sprite name="arrow-up" texture="gui/widget.png"><frame>132 56 5 4</frame></sprite>

<sprite name="box" texture="gui/playermenu.png"><frame>337 2 28 28</frame></sprite>
<sprite name="box-wide" texture="gui/playermenu.png"><frame>367 0 44 28</frame></sprite>
<sprite name="char-shadow" texture="gui/widget.png"><frame>99 118 12 12</frame></sprite>

<sprite name="merc-small-left" texture="gui/widget.png"><frame>378 24 7 24</frame></sprite>
<sprite name="merc-small-right" texture="gui/widget.png"><frame>385 24 6 24</frame></sprite>

<sprite name="merc-left" texture="gui/widget.png"><frame>211 72 14 24</frame></sprite>
<sprite name="merc-right" texture="gui/widget.png"><frame>225 72 13 24</frame></sprite>

%if LEDGER_BUTTON
<sprite name="char-button24-frame" texture="gui/widget.png"><frame>76 182 28 28</frame></sprite>
<sprite name="char-button24" texture="gui/widget.png"><frame>33 130 24 24</frame></sprite>
<sprite name="char-button24-hover" texture="gui/widget.png"><frame>57 130 24 24</frame></sprite>
<sprite name="char-button24-down" texture="gui/widget.png"><frame>81 130 24 24</frame></sprite>

<sprite name="icon-char-delete" texture="gui/icons.png"><frame>22 76 9 12</frame></sprite>
%endif
