<!-- Big -->
<sprite name="scalebutton-big-left" texture="gui/widget.png"><frame>0 98 16 32</frame></sprite>
<sprite name="scalebutton-big-mid" texture="gui/widget.png"><frame>16 98 1 32</frame></sprite>
<sprite name="scalebutton-big-right" texture="gui/widget.png"><frame>17 98 16 32</frame></sprite>

<sprite name="scalebutton-big-hover-left" texture="gui/widget.png"><frame>33 98 16 32</frame></sprite>
<sprite name="scalebutton-big-hover-mid" texture="gui/widget.png"><frame>49 98 1 32</frame></sprite>
<sprite name="scalebutton-big-hover-right" texture="gui/widget.png"><frame>50 98 16 32</frame></sprite>

<sprite name="scalebutton-big-down-left" texture="gui/widget.png"><frame>66 98 16 32</frame></sprite>
<sprite name="scalebutton-big-down-mid" texture="gui/widget.png"><frame>82 98 1 32</frame></sprite>
<sprite name="scalebutton-big-down-right" texture="gui/widget.png"><frame>83 98 16 32</frame></sprite>

<!-- Big disabled -->
<sprite name="scalebutton-big-disabled-left" texture="gui/widget.png"><frame>0 130 16 32</frame></sprite>
<sprite name="scalebutton-big-disabled-mid" texture="gui/widget.png"><frame>16 130 1 32</frame></sprite>
<sprite name="scalebutton-big-disabled-right" texture="gui/widget.png"><frame>17 130 16 32</frame></sprite>
