<sprite name="check-left" texture="gui/widget.png"><frame>128 178 37 26</frame></sprite>
<sprite name="check-mid" texture="gui/widget.png"><frame>165 178 1 26</frame></sprite>
<sprite name="check-right" texture="gui/widget.png"><frame>166 178 37 26</frame></sprite>

<sprite name="check-hover-left" texture="gui/widget.png"><frame>128 204 37 26</frame></sprite>
<sprite name="check-hover-mid" texture="gui/widget.png"><frame>165 204 1 26</frame></sprite>
<sprite name="check-hover-right" texture="gui/widget.png"><frame>166 204 37 26</frame></sprite>

<sprite name="check-down-left" texture="gui/widget.png"><frame>128 230 37 26</frame></sprite>
<sprite name="check-down-mid" texture="gui/widget.png"><frame>165 230 1 26</frame></sprite>
<sprite name="check-down-right" texture="gui/widget.png"><frame>166 230 37 26</frame></sprite>

<sprite name="check-disabled-left" texture="gui/widget.png"><frame>128 152 37 26</frame></sprite>
<sprite name="check-disabled-mid" texture="gui/widget.png"><frame>165 152 1 26</frame></sprite>
<sprite name="check-disabled-right" texture="gui/widget.png"><frame>166 152 37 26</frame></sprite>
