<!-- Regular -->
<sprite name="scalebutton-left" texture="gui/widget.png"><frame>0 24 16 18</frame></sprite>
<sprite name="scalebutton-mid" texture="gui/widget.png"><frame>16 24 1 18</frame></sprite>
<sprite name="scalebutton-right" texture="gui/widget.png"><frame>17 24 16 18</frame></sprite>

<sprite name="scalebutton-hover-left" texture="gui/widget.png"><frame>0 42 16 18</frame></sprite>
<sprite name="scalebutton-hover-mid" texture="gui/widget.png"><frame>16 42 1 18</frame></sprite>
<sprite name="scalebutton-hover-right" texture="gui/widget.png"><frame>17 42 16 18</frame></sprite>

<sprite name="scalebutton-down-left" texture="gui/widget.png"><frame>0 60 16 18</frame></sprite>
<sprite name="scalebutton-down-mid" texture="gui/widget.png"><frame>16 60 1 18</frame></sprite>
<sprite name="scalebutton-down-right" texture="gui/widget.png"><frame>17 60 16 18</frame></sprite>

<!-- Regular disabled -->
<sprite name="scalebutton-disabled-left" texture="gui/widget.png"><frame>0 78 16 18</frame></sprite>
<sprite name="scalebutton-disabled-mid" texture="gui/widget.png"><frame>16 78 1 18</frame></sprite>
<sprite name="scalebutton-disabled-right" texture="gui/widget.png"><frame>17 78 16 18</frame></sprite>
