<sprite name="scrollbar-handle" texture="gui/widget.png"><frame>33 28 6 14</frame></sprite>
<sprite name="scrollbar-handle-hover" texture="gui/widget.png"><frame>39 28 6 14</frame></sprite>
<sprite name="scrollbar-handle-pressed" texture="gui/widget.png"><frame>45 28 6 14</frame></sprite>

<sprite name="scrollbar-button-up" texture="gui/widget.png"><frame>33 0 8 14</frame></sprite>
<sprite name="scrollbar-button-up-hover" texture="gui/widget.png"><frame>41 0 8 14</frame></sprite>
<sprite name="scrollbar-button-up-pressed" texture="gui/widget.png"><frame>49 0 8 14</frame></sprite>
<sprite name="scrollbar-button-up-disabled" texture="gui/widget.png"><frame>57 0 8 14</frame></sprite>

<sprite name="scrollbar-button-down" texture="gui/widget.png"><frame>33 14 8 14</frame></sprite>
<sprite name="scrollbar-button-down-hover" texture="gui/widget.png"><frame>41 14 8 14</frame></sprite>
<sprite name="scrollbar-button-down-pressed" texture="gui/widget.png"><frame>49 14 8 14</frame></sprite>
<sprite name="scrollbar-button-down-disabled" texture="gui/widget.png"><frame>57 14 8 14</frame></sprite>

<sprite name="scrollbar-trough-top" texture="gui/widget.png"><frame>65 0 8 20</frame></sprite>
<sprite name="scrollbar-trough-middle" texture="gui/widget.png"><frame>65 20 8 1</frame></sprite>
<sprite name="scrollbar-trough-bottom" texture="gui/widget.png"><frame>65 21 8 20</frame></sprite>

<sprite name="scrollbar-trough-disabled-top" texture="gui/widget.png"><frame>73 0 8 20</frame></sprite>
<sprite name="scrollbar-trough-disabled-middle" texture="gui/widget.png"><frame>73 20 8 1</frame></sprite>
<sprite name="scrollbar-trough-disabled-bottom" texture="gui/widget.png"><frame>73 21 8 20</frame></sprite>
