<dict>
	<string name="prefab">prefabs/moon_temple_poor/512x512/512x512_cap_n_selector.pfb</string>
	<array name="layout">
		<a><s>x</s><s>x</s></a>
		<a><s>s</s><s>s</s></a>
	</array>
	
	<int name="chance">1</int>
	<string name="reqs">large_room</string>
</dict>

<dict>
	<string name="prefab">prefabs/moon_temple_poor/512x512/512x512_cap_s_selector.pfb</string>
	<array name="layout">
		<a><s>n</s><s>n</s></a>
		<a><s>x</s><s>x</s></a>
	</array>
	
	<int name="chance">1</int>
	<string name="reqs">large_room</string>
</dict>

<dict>
	<string name="prefab">prefabs/moon_temple_poor/512x512/512x512_sides_v_selector.pfb</string>
	<array name="layout">
		<a><s>n</s><s>n</s></a>
		<a><s>s</s><s>s</s></a>
	</array>
	
	<int name="chance">1</int>
	<string name="reqs">large_room</string>
</dict>