<dict>
	<string name="prefab">prefabs/moon_temple_poor/256x256/256x256_cap_n_chest_selector.pfb</string>
	<array name="layout">
		<a><s>s</s></a>
	</array>
	
	<int name="chance">1</int>
	<string name="reqs">chest</string>
	<!-- <string name="placement">spread</string> -->
</dict>
<dict>
	<string name="prefab">prefabs/moon_temple_poor/256x256/256x256_cap_s_chest_selector.pfb</string>
	<array name="layout">
		<a><s>n</s></a>
	</array>
	
	<int name="chance">1</int>
	<string name="reqs">chest</string>
	<!-- <string name="placement">spread</string> -->
</dict>
<dict>
	<string name="prefab">prefabs/moon_temple_poor/256x256/256x256_cap_e_chest_selector.pfb</string>
	<array name="layout">
		<a><s>w</s></a>
	</array>
	
	<int name="chance">1</int>
	<string name="reqs">chest</string>
	<!-- <string name="placement">spread</string> -->
</dict>
<dict>
	<string name="prefab">prefabs/moon_temple_poor/256x256/256x256_cap_w_chest_selector.pfb</string>
	<array name="layout">
		<a><s>e</s></a>
	</array>
	
	<int name="chance">1</int>
	<string name="reqs">chest</string>
	<!-- <string name="placement">spread</string> -->
</dict>

<dict>
	<string name="prefab">prefabs/moon_temple_poor/256x512/256x512_cap_n_chest_selector.pfb</string>
	<array name="layout">
		<a><s>x</s></a>
		<a><s>s</s></a>
	</array>
	
	<int name="chance">1</int>
	<string name="reqs">chest</string>
	<!-- <string name="placement">spread</string> -->
</dict>
<dict>
	<string name="prefab">prefabs/moon_temple_poor/256x512/256x512_cap_s_chest_selector.pfb</string>
	<array name="layout">
		<a><s>n</s></a>
		<a><s>x</s></a>
	</array>
	
	<int name="chance">1</int>
	<string name="reqs">chest</string>
	<!-- <string name="placement">spread</string> -->
</dict>

<dict>
	<string name="prefab">prefabs/moon_temple_poor/512x256/512x256_cap_e_chest_selector.pfb</string>
	<array name="layout">
		<a><s>w</s><s>x</s></a>
	</array>
	
	<int name="chance">1</int>
	<string name="reqs">chest</string>
	<!-- <string name="placement">spread</string> -->
</dict>
<dict>
	<string name="prefab">prefabs/moon_temple_poor/512x256/512x256_cap_w_chest_selector.pfb</string>
	<array name="layout">
		<a><s>x</s><s>e</s></a>
	</array>
	
	<int name="chance">1</int>
	<string name="reqs">chest</string>
	<!-- <string name="placement">spread</string> -->
</dict>

