<dict>
	<string name="prefab">prefabs/moon_temple_poor/256x256/256x256_gt_cap_n.pfb</string>
	<array name="layout">
		<a><s>S</s></a>
	</array>
	
	<bool name="hidden">true</bool>
	<int name="chance">1</int>
	<string name="reqs">gt</string>
	<!-- <string name="placement">spread</string> -->
</dict>
<dict>
	<string name="prefab">prefabs/moon_temple_poor/256x256/256x256_gt_cap_s.pfb</string>
	<array name="layout">
		<a><s>N</s></a>
	</array>
	
	<bool name="hidden">true</bool>
	<int name="chance">1</int>
	<string name="reqs">gt</string>
	<!-- <string name="placement">spread</string> -->
</dict>


<dict>
	<string name="prefab">prefabs/moon_temple_poor/256x256/256x256_gt_cap_w.pfb</string>
	<array name="layout">
		<a><s>E</s></a>
	</array>
	
	<bool name="hidden">true</bool>
	<int name="chance">0</int>
	<string name="reqs">gt</string>
	<!-- <string name="placement">spread</string> -->
</dict>
<dict>
	<string name="prefab">prefabs/moon_temple_poor/256x256/256x256_gt_cap_e.pfb</string>
	<array name="layout">
		<a><s>W</s></a>
	</array>
	
	<bool name="hidden">true</bool>
	<int name="chance">0</int>
	<string name="reqs">gt</string>
	<!-- <string name="placement">spread</string> -->
</dict>