<dict>
	<string name="prefab">prefabs/moon_temple_poor/512x256/512x256_crn_ne_selector.pfb</string>
	<array name="layout">
		<a><s>sw</s><s>s</s></a>
	</array>
	
	<int name="chance">2</int>
</dict>
<dict>
	<string name="prefab">prefabs/moon_temple_poor/512x256/512x256_crn_nw_selector.pfb</string>
	<array name="layout">
		<a><s>s</s><s>se</s></a>
	</array>
	
	<int name="chance">2</int>
</dict>
<dict>
	<string name="prefab">prefabs/moon_temple_poor/512x256/512x256_crn_se_selector.pfb</string>
	<array name="layout">
		<a><s>nw</s><s>n</s></a>
	</array>
	
	<int name="chance">2</int>
</dict>
<dict>
	<string name="prefab">prefabs/moon_temple_poor/512x256/512x256_crn_sw_selector.pfb</string>
	<array name="layout">
		<a><s>n</s><s>ne</s></a>
	</array>
	
	<int name="chance">2</int>
</dict>