<dict>
	<string name="prefab">prefabs/moon_temple_poor/512x256/512x256_cap_n_selector.pfb</string>
	<array name="layout">
		<a><s>s</s><s>s</s></a>
	</array>
	
	<int name="chance">2</int>
	<string name="reqs">medium_cap</string>
</dict>
<dict>
	<string name="prefab">prefabs/moon_temple_poor/512x256/512x256_cap_s_selector.pfb</string>
	<array name="layout">
		<a><s>n</s><s>n</s></a>
	</array>
	
	<int name="chance">2</int>
	<string name="reqs">medium_cap</string>
</dict>

<dict>
	<string name="prefab">prefabs/moon_temple_poor/512x256/512x256_sides_v_selector.pfb</string>
	<array name="layout">
		<a><s>ns</s><s>ns</s></a>
	</array>
	
	<int name="chance">2</int>
	<string name="reqs">medium_cap</string>
</dict>