<dict>
	<string name="prefab">prefabs/moon_temple_poor/256x512/256x512_room_selector.pfb</string>
	<array name="layout">
		<a><s>nwe</s></a>
		<a><s>swe</s></a>
	</array>
	
	<int name="chance">5</int>
</dict>

<dict>
	<string name="prefab">prefabs/moon_temple_poor/256x512/256x512_diag_ne_sw_selector.pfb</string>
	<array name="layout">
		<a><s>ne</s></a>
		<a><s>sw</s></a>
	</array>
	
	<int name="chance">5</int>
</dict>
<dict>
	<string name="prefab">prefabs/moon_temple_poor/256x512/256x512_diag_nw_se_selector.pfb</string>
	<array name="layout">
		<a><s>nw</s></a>
		<a><s>se</s></a>
	</array>
	
	<int name="chance">5</int>
</dict>

<dict>
	<string name="prefab">prefabs/moon_temple_poor/256x512/256x512_x_n_long_selector.pfb</string>
	<array name="layout">
		<a><s>we</s></a>
		<a><s>s</s></a>
	</array>
	
	<int name="chance">5</int>
</dict>
<dict>
	<string name="prefab">prefabs/moon_temple_poor/256x512/256x512_x_n_selector.pfb</string>
	<array name="layout">
		<a><s>x</s></a>
		<a><s>swe</s></a>
	</array>
	
	<int name="chance">5</int>
</dict>
<dict>
	<string name="prefab">prefabs/moon_temple_poor/256x512/256x512_x_s_long_selector.pfb</string>
	<array name="layout">
		<a><s>n</s></a>
		<a><s>we</s></a>
	</array>
	
	<int name="chance">5</int>
</dict>
<dict>
	<string name="prefab">prefabs/moon_temple_poor/256x512/256x512_x_s_selector.pfb</string>
	<array name="layout">
		<a><s>nwe</s></a>
		<a><s>x</s></a>
	</array>
	
	<int name="chance">5</int>
</dict>