<dict>
	<string name="prefab">prefabs/moon_temple_rich/disconnected/1x3_chest_selector.pfb</string>
	<array name="layout">
		<a><s>x</s></a>
		<a><s>x</s></a>
		<a><s>x</s></a>
	</array>

	<int name="chance">0</int>
	<string name="reqs">disconnected</string>
</dict>

<dict>
	<string name="prefab">prefabs/moon_temple_rich/disconnected/2x2_chest_selector.pfb</string>
	<array name="layout">
		<a><s>x</s><s>x</s></a>
		<a><s>x</s><s>x</s></a>
	</array>
	
	<int name="chance">0</int>
	<string name="reqs">disconnected</string>
</dict>


<dict>
	<string name="prefab">prefabs/moon_temple_rich/disconnected/2x3_chest_selector.pfb</string>
	<array name="layout">
		<a><s>x</s><s>x</s></a>
		<a><s>x</s><s>x</s></a>
		<a><s>x</s><s>x</s></a>
	</array>
	
	<int name="chance">0</int>
	<string name="reqs">disconnected2</string>
</dict>

<dict>
	<string name="prefab">prefabs/moon_temple_rich/disconnected/3x2_chest_selector.pfb</string>
	<array name="layout">
		<a><s>x</s><s>x</s><s>x</s></a>
		<a><s>x</s><s>x</s><s>x</s></a>
	</array>

	<int name="chance">0</int>
	<string name="reqs">disconnected2</string>
</dict>


<dict>
	<string name="prefab">prefabs/moon_temple_rich/disconnected/3x1_chest_selector.pfb</string>
	<array name="layout">
		<a><s>x</s><s>x</s><s>x</s></a>
	</array>

	<int name="chance">0</int>
	<string name="reqs">disconnected3</string>
</dict>

<dict>
	<string name="prefab">prefabs/moon_temple_rich/disconnected/3x3_chest_selector.pfb</string>
	<array name="layout">
		<a><s>x</s><s>x</s><s>x</s></a>
		<a><s>x</s><s>x</s><s>x</s></a>
		<a><s>x</s><s>x</s><s>x</s></a>
	</array>
	
	<int name="chance">0</int>
	<string name="reqs">disconnected3</string>
</dict>

<!-- MORE CHEST ROOMS -->
<dict>
	<string name="prefab">prefabs/moon_temple_rich/disconnected/2x2_chest_selector.pfb</string>
	<array name="layout">
		<a><s>x</s><s>x</s></a>
		<a><s>x</s><s>x</s></a>
	</array>
	
	<int name="chance">3</int>
	<string name="reqs">disconnected_more</string>
</dict>

<dict>
	<string name="prefab">prefabs/moon_temple_rich/disconnected/2x3_chest_selector.pfb</string>
	<array name="layout">
		<a><s>x</s><s>x</s></a>
		<a><s>x</s><s>x</s></a>
		<a><s>x</s><s>x</s></a>
	</array>
	
	<int name="chance">3</int>
	<string name="reqs">disconnected_more</string>
</dict>