<dict>
	<string name="prefab">prefabs/moon_temple_rich/256x256/256x256_hallway_v_selector.pfb</string>
	<array name="layout">
		<a><s>NS</s></a>
	</array>
	
	<int name="chance">1</int>
	<string name="reqs">hallway</string>
</dict>

<dict>
	<string name="prefab">prefabs/moon_temple_rich/256x256/256x256_hallway_h_selector.pfb</string>
	<array name="layout">
		<a><s>WE</s></a>
	</array>
	
	<int name="chance">1</int>
	<string name="reqs">hallway</string>
</dict>