<dict>
	<string name="prefab">prefabs/moon_temple_rich/512x512/512x512_room_objective_selector.pfb</string>
	<array name="layout">
		<a><s>nw</s><s>ne</s></a>
		<a><s>sw</s><s>se</s></a>
	</array>
	
	<int name="chance">1</int>
	<string name="reqs">objective1</string>
</dict>

<dict>
	<string name="prefab">prefabs/moon_temple_rich/512x512/512x512_cap_n_objective_objective_selector.pfb</string>
	<array name="layout">
		<a><s>x</s><s>x</s></a>
		<a><s>s</s><s>s</s></a>
	</array>
	
	<int name="chance">1</int>
	<string name="reqs">objective2</string>
	<!-- <string name="placement">top</string> -->
</dict>

<dict>
	<string name="prefab">prefabs/moon_temple_rich/512x512/512x512_cap_s_objective_selector.pfb</string>
	<array name="layout">
		<a><s>n</s><s>n</s></a>
		<a><s>x</s><s>x</s></a>
	</array>
	
	<int name="chance">1</int>
	<string name="reqs">objective2</string>
	<!-- <string name="placement">bottom</string> -->
</dict>

<dict>
	<string name="prefab">prefabs/moon_temple_rich/512x512/512x512_cap_e_objective_selector.pfb</string>
	<array name="layout">
		<a><s>w</s><s>x</s></a>
		<a><s>w</s><s>x</s></a>
	</array>
	
	<int name="chance">1</int>
	<string name="reqs">objective3</string>
	<!-- <string name="placement">left</string> -->
</dict>

<dict>
	<string name="prefab">prefabs/moon_temple_rich/512x512/512x512_cap_w_objective_selector.pfb</string>
	<array name="layout">
		<a><s>x</s><s>e</s></a>
		<a><s>x</s><s>e</s></a>
	</array>
	
	<int name="chance">1</int>
	<string name="reqs">objective3</string>
	<!-- <string name="placement">right</string> -->
</dict>