<dict>
	<string name="prefab">prefabs/moon_temple_rich/256x256/256x256_room_selector.pfb</string>
	<array name="layout">
		<a><s>nswe</s></a>
	</array>
	
	<int name="chance">10</int>
</dict>

<dict>
	<string name="prefab">prefabs/moon_temple_rich/256x256/256x256_x_n_selector.pfb</string>
	<array name="layout">
		<a><s>swe</s></a>
	</array>
	
	<int name="chance">5</int>
</dict>
<dict>
	<string name="prefab">prefabs/moon_temple_rich/256x256/256x256_x_s_selector.pfb</string>
	<array name="layout">
		<a><s>nwe</s></a>
	</array>
	
	<int name="chance">5</int>
</dict>		
<dict>
	<string name="prefab">prefabs/moon_temple_rich/256x256/256x256_x_w_selector.pfb</string>
	<array name="layout">
		<a><s>nse</s></a>
	</array>
	
	<int name="chance">5</int>
</dict>
<dict>
	<string name="prefab">prefabs/moon_temple_rich/256x256/256x256_x_e_selector.pfb</string>
	<array name="layout">
		<a><s>nsw</s></a>
	</array>
	
	<int name="chance">5</int>
</dict>