<dict>
	<string name="prefab">prefabs/moon_temple_rich/512x512/512x512_room_selector.pfb</string>
	<array name="layout">
		<a><s>nw</s><s>ne</s></a>
		<a><s>sw</s><s>se</s></a>
	</array>
	
	<int name="chance">10</int>
</dict>

<dict>
	<string name="prefab">prefabs/moon_temple_rich/512x512/512x512_x_e_wide_selector.pfb</string>
	<array name="layout">
		<a><s>nw</s><s>n</s></a>
		<a><s>sw</s><s>s</s></a>
	</array>
	
	<int name="chance">5</int>
</dict>
<dict>
	<string name="prefab">prefabs/moon_temple_rich/512x512/512x512_x_n_wide_selector.pfb</string>
	<array name="layout">
		<a><s>w</s><s>e</s></a>
		<a><s>sw</s><s>se</s></a>
	</array>
	
	<int name="chance">5</int>
</dict>
<dict>
	<string name="prefab">prefabs/moon_temple_rich/512x512/512x512_x_s_wide_selector.pfb</string>
	<array name="layout">
		<a><s>nw</s><s>ne</s></a>
		<a><s>w</s><s>e</s></a>
	</array>
	
	<int name="chance">5</int>
</dict>
<dict>
	<string name="prefab">prefabs/moon_temple_rich/512x512/512x512_x_w_wide_selector.pfb</string>
	<array name="layout">
		<a><s>n</s><s>ne</s></a>
		<a><s>s</s><s>se</s></a>
	</array>
	
	<int name="chance">5</int>
</dict>