<dict>
	<string name="prefab">prefabs/moon_temple_rich/512x256/512x256_room_selector.pfb</string>
	<array name="layout">
		<a><s>nsw</s><s>nse</s></a>
	</array>
	
	<int name="chance">10</int>
</dict>

<dict>
	<string name="prefab">prefabs/moon_temple_rich/512x256/512x256_diag_ne_sw_selector.pfb</string>
	<array name="layout">
		<a><s>sw</s><s>ne</s></a>
	</array>
	
	<int name="chance">5</int>
</dict>
<dict>
	<string name="prefab">prefabs/moon_temple_rich/512x256/512x256_diag_nw_se_selector.pfb</string>
	<array name="layout">
		<a><s>nw</s><s>se</s></a>
	</array>
	
	<int name="chance">5</int>
</dict>

<dict>
	<string name="prefab">prefabs/moon_temple_rich/512x256/512x256_x_e_long_selector.pfb</string>
	<array name="layout">
		<a><s>w</s><s>ns</s></a>
	</array>
	
	<int name="chance">5</int>
</dict>
<dict>
	<string name="prefab">prefabs/moon_temple_rich/512x256/512x256_x_e_selector.pfb</string>
	<array name="layout">
		<a><s>nsw</s><s>x</s></a>
	</array>
	
	<int name="chance">5</int>
</dict>
<dict>
	<string name="prefab">prefabs/moon_temple_rich/512x256/512x256_x_w_long_selector.pfb</string>
	<array name="layout">
		<a><s>ns</s><s>e</s></a>
	</array>
	
	<int name="chance">5</int>
</dict>
<dict>
	<string name="prefab">prefabs/moon_temple_rich/512x256/512x256_x_w_selector.pfb</string>
	<array name="layout">
		<a><s>x</s><s>nse</s></a>
	</array>
	
	<int name="chance">5</int>
</dict>